"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Profiling: default = Silk; DDT=TRUE → Django Debug Toolbar (no Silk)
def _env_true(name: str) -> bool:
    return os.environ.get(name, "").upper() in ("TRUE", "1", "YES")


USE_DDT = _env_true("DDT")
USE_SILK = not USE_DDT

if USE_SILK:
    SILKY_PYTHON_PROFILER = False  # keep Silk request/SQL recording only; no cProfile
    SILKY_META = (
        True  # mostra tempo que o Silk leva para salvar (impacto do próprio Silk)
    )
    # SILKY_STORAGE still needed for Silk internals
    from django.conf.global_settings import STORAGES as _DEFAULT_STORAGES

    STORAGES = {
        **_DEFAULT_STORAGES,
        "SILKY_STORAGE": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {},
            "LOCATION": str(BASE_DIR / "silk_profiles"),
        },
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-e47p@^9(yu(wy9cv12!$kpr8&4c298o8r6%k0%ajt@)oy_8q9l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

INTERNAL_IPS = ["127.0.0.1"]


# Application definition

_profiling_apps = []
if USE_SILK:
    _profiling_apps.append("silk")
if USE_DDT:
    _profiling_apps.append("debug_toolbar")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    *_profiling_apps,
    "django_browser_reload",
    "casas_floripa",
]

AUTH_USER_MODEL = "casas_floripa.Usuario"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    *(["silk.middleware.SilkyMiddleware"] if USE_SILK else []),
    *(["debug_toolbar.middleware.DebugToolbarMiddleware"] if USE_DDT else []),
]


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db_02.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
