# Generated by Django 6.0.2 on 2026-02-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casas_floripa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="vector_embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="vector_embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
