# Generated by Django 6.0.2 on 2026-02-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casas_floripa", "0002_add_vector_embedding_cliente_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="vector_embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
