# Generated by Django 6.0.2 on 2026-02-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casas_floripa", "0003_add_vector_embedding_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="vector_embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
