# Generated by Django 6.0.2 on 2026-02-17 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas_floripa', '0003_categoria_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10)),
                ('desconto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas_floripa.cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casas_floripa.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='casas_floripa.pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
    ]
