# Generated by Django 6.0.2 on 2026-02-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casas_floripa", "0005_alter_categoria_id_alter_cliente_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="vector_embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
