# Generated by Django 6.0.2 on 2026-02-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casas_floripa", "0006_add_produto_vector_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="vector_embedding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="vector_embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
